servicedata: 
 service:
  id: 1001
  svcName: HTTP APIs
  description: Select the units, number, and frequency for HTTP
  svcFormula: price(total_requests)
  serviceDimensions:
    -  
     svcDimName: total_requests
     dimensionType: DERIVED
     value: requests * request_unit * period * ((sizebytes-1)/512)+1);
    -
      svcDimName: request_unit
      dimensionType: PICKLIST
      picklist:
        -
         name: exact number
         value: 1
        - 
         name: thousands
         value: 1000
        - 
         name: millions
         value: 1000000
        -
         name: billions
         value: 10000000
     
    -
      svcDimName: period
      dimensionType: PICKLIST
      picklist:
        -
         name: per second
         value: 2628000000
        -
         name: per minute
         value: 43800000
        -
         name: per hour
         value: 730000
        -
         name: per day
         value: 30416
        - 
         name: per month
         value: 1
    -  
     svcDimName: sizebytes
     dimensionType: PICKLIST
     picklist:
       -
        name: bytes
        value: 0.000976563
       -
        name: kb
        value: 1
       -
        name: mb
        value: 1024
    -  
     svcDimName: requests
     dimensionType: INPUT
    -  
     svcDimName: sizeunit
     dimensionType: INPUT
   
     
 rateTables:
        -
         
         priceMethod: TIERED
         maxValue: 1
         minValue: 300000000
         unitPrice: 0.000001
         svcDimName: total_requests
        -
         priceMethod: TIERED
         maxValue: 300000000
         minValue: 1000000000
         unitPrice: 0.0000009
         svcDimName: total_requests
         
estimation:
  eventData:
    - 
     name: request_unit
     value: thousands
    -
     name: period
     value: per month
    -
     name: requests
     value: 1000
    -
     name: sizeunit
     value: 1000
    -
     name: sizebytes
     value: 756